from typing import Protocol

from entity_disambiguator_py.model import (
    BatchGetAliasNameResponse,
    BatchGetAliasResponse,
    BatchGetConceptResponse,
    CanonicalSynonymsResponse,
    GetAliasNameResponse,
    GetAliasResponse,
    GetConceptResponse,
    GetNeighborsResponse,
    GraphTraversalResponse,
    SynonymSetResponse,
)


class UMLSDbInterface(Protocol):
    def get_alias_id(self, alias_id: str) -> GetAliasResponse: ...
    def get_batch_alias_id(self, alias_ids: list[str]) -> BatchGetAliasResponse: ...
    def get_alias_name(self, alias_name: str) -> GetAliasNameResponse: ...
    def get_batch_alias_name(self, names: list[str]) -> BatchGetAliasNameResponse: ...
    def get_concept(self, concept_id: str) -> GetConceptResponse: ...
    def get_batch_concept(self, concept_ids: list[str]) -> BatchGetConceptResponse: ...
    def get_synonym_set(self, ssid: str) -> SynonymSetResponse: ...
    def get_canonical_synoyms(self, cid: str) -> CanonicalSynonymsResponse: ...
    def get_parents(self, umls_id: str, sort_prefix: str) -> GetNeighborsResponse: ...
    def get_children(self, umls_id: str, sort_prefix: str) -> GetNeighborsResponse: ...
    def get_neighbors(self, umls_id: str, sort_prefix: str) -> GetNeighborsResponse: ...
    def get_ancestors(self, umls_id: str, sort_prefix: str) -> GraphTraversalResponse: ...
    def get_descendants(self, umls_id: str, sort_prefix: str) -> GraphTraversalResponse: ...
    def get_subgraph(self, umls_id: str, sort_prefix: str) -> GraphTraversalResponse: ...
